# Generated by Django 3.1.2 on 2021-03-30 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='Цена товара')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_product.product', verbose_name='Товар')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_product.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Склад товара',
                'verbose_name_plural': 'Склады товаров',
                'unique_together': {('product', 'store')},
            },
        ),
    ]
