# Generated by Django 3.1.2 on 2021-04-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0004_cart_purchasehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки'),
        ),
    ]
