# Generated by Django 3.1.2 on 2021-03-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_auto_20210329_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Бронзовый', 'Бронзовый'), ('Серебрянный', 'Серебрянный'), ('Золотой', 'Золотой')], max_length=20, verbose_name='Статус'),
        ),
    ]
