# Generated by Django 2.2 on 2021-04-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created_date',
            field=models.DateField(null=True, verbose_name='Дата создания'),
        ),
    ]
