# Generated by Django 3.2 on 2021-04-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
