# Generated by Django 3.2 on 2021-04-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_property', '0002_alter_housingtype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomsNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Количество комнат')),
            ],
            options={
                'verbose_name': 'Количество комнат',
                'verbose_name_plural': 'Количества комнат',
            },
        ),
    ]
