# Generated by Django 2.2 on 2021-04-11 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_property', '0003_roomsnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingtype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='roomsnumber',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField(verbose_name='Стоимость')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('created_date', models.DateField(verbose_name='Дата постройки/сдачи')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Флаг продано/непродано')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('housing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_property.HousingType', verbose_name='Тип помещения')),
                ('rooms_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_property.RoomsNumber', verbose_name='Количество комнат')),
            ],
            options={
                'verbose_name': 'Жильё',
                'verbose_name_plural': 'Жильё',
            },
        ),
    ]
