# Generated by Django 2.2 on 2021-04-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_property', '0004_auto_20210411_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
